services:
  flask-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres
    working_dir: /app

  postgres:
    image: postgres:14.5-bullseye
    container_name: mh-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "mentalhealth_db"
    volumes:
      - mhdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: mh-db-admin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASSWORD}
    ports:
      - "5050:80"


volumes:
  mhdata:
    name: mhdata