services:
  flask-app:
    build: .
    image: aarooon16045/mh-app:${IMAGE_TAG}
    ports:
      - "5001:5001"
    restart: on-failure
    depends_on:
      - postgres
    # debugging
    # volumes:
    #   - .:/app
    working_dir: /app
    # command:  ["flask", "run", "--host=0.0.0.0", "--port=5001", "--debug"]
    command: ["waitress-serve", "--host=0.0.0.0", "--port=5001", "app:app"]
    env_file:
      - .env

  postgres:
    image: postgres:14.5-bullseye
    container_name: mh-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "mentalhealth_db"
    volumes:
      - mhdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: mh-db-admin
    restart: on-failure
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASSWORD}
    ports:
      - "5050:80"


volumes:
  mhdata:
    name: mhdata