services:
  flask-app:
    build: .
    image: aarooon16045/mh-app:${IMAGE_TAG}
    ports:
      - "5001:5001"
    restart: on-failure
    # debugging
    volumes:
      - .:/app
    working_dir: /app
    # command:  ["flask", "run", "--host=0.0.0.0", "--port=5001", "--debug"]
    command: ["waitress-serve", "--host=0.0.0.0", "--port=5001", "app:app"]
    env_file:
      - .env
    networks:
      - database-network

networks:
  database-network:
    external: true