services:
  flask-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - sqlite-db

  sqlite-db:
    image: busybox
    volumes:
      - sqlite_data:/app/mentalhealth.db

volumes:
  sqlite_data: